-- price snapshots
create table if not exists prices (
  id bigint generated by default as identity primary key,
  weth_price numeric not null,
  rore_price numeric not null,
  created_at timestamptz default now()
);

-- round results with computed motherlode
create table if not exists rounds (
  round_id integer primary key,
  motherlode numeric,
  motherlode_hit boolean not null default false,
  motherlode_running numeric not null default 0,
  prize numeric not null default 0,
  entries integer not null default 0,
  status text not null default 'Unknown',
  end_time timestamptz not null,
  block integer check (block between 1 and 25),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_rounds_block on rounds(block);
create index if not exists idx_rounds_status on rounds(status);
create index if not exists idx_rounds_round_id on rounds(round_id);

-- aggregated protocol metrics
create table if not exists protocol_stats (
  id bigint generated by default as identity primary key,
  total_value numeric not null default 0,
  total_ore_locked numeric not null default 0,
  participants integer not null default 0,
  created_at timestamptz default now()
);

-- sync job logs
create table if not exists sync_log (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  status text not null,
  records_ingested integer not null default 0,
  error_message text,
  started_at timestamptz not null,
  completed_at timestamptz not null
);
